/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package TodoListApp;
import javax.swing.*;
import java.io.* ;
import java.util.Scanner;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rakshit Kaushal
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        setDataToTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_task = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        Taks_label = new javax.swing.JLabel();
        task_input = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tasks_table = new javax.swing.JTable();
        delete_task = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_task.setBackground(new java.awt.Color(51, 255, 51));
        add_task.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add_task.setForeground(new java.awt.Color(255, 255, 255));
        add_task.setText("Add Task");
        add_task.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_taskActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        heading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("TODO LIST");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(heading)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        Taks_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Taks_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Taks_label.setText("Task");

        tasks_table.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        tasks_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tasks_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tasks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tasks_table);

        delete_task.setBackground(new java.awt.Color(255, 0, 51));
        delete_task.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete_task.setForeground(new java.awt.Color(255, 255, 255));
        delete_task.setText("Delete Task");
        delete_task.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_taskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Taks_label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(task_input))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_task))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(delete_task))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_task)
                    .addComponent(Taks_label)
                    .addComponent(task_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_task))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Taks_label, add_task, delete_task, task_input});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
private void setDataToTable() {
    DefaultTableModel dtm = (DefaultTableModel) tasks_table.getModel();
    int row_count = dtm.getRowCount();
    for (int i = row_count - 1; i >= 0; i--) {
        dtm.removeRow(i);
    }

    try {
        FileInputStream f = new FileInputStream("task.txt");
        Scanner sc = new Scanner(f);
        
        while (sc.hasNextLine()) {
            try {
                Vector<String> row = new Vector<>();
                row.add(sc.nextLine());
                dtm.addRow(row);
            } catch (Exception ex) {
                break;
            }
        }
        
        sc.close();
        f.close();
    } catch (Exception E) {
        JOptionPane.showMessageDialog(null, E.getMessage());
    }
}
    private void add_taskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_taskActionPerformed
        try{
            FileOutputStream f = new FileOutputStream("task.txt", true);
            PrintStream p=new PrintStream(f);
            String task = task_input.getText();
            if (task == null || task.isEmpty()) {
                throw new Exception("Task is empty");
            }
            p.println(task);
            p.close();
            f.close();
            task_input.setText("");
            setDataToTable();
        }
        catch(Exception E){
            JOptionPane.showMessageDialog(null, E.getMessage());
        }
    }//GEN-LAST:event_add_taskActionPerformed

    private void delete_taskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_taskActionPerformed
                                       
    int selectedRow = tasks_table.getSelectedRow();
    if (selectedRow != -1) {
        DefaultTableModel dtm = (DefaultTableModel) tasks_table.getModel();
        String taskToDelete = (String) dtm.getValueAt(selectedRow, 0);

        // Remove the row from the table
        dtm.removeRow(selectedRow);

        // Remove the task from the file
        try {
            File inputFile = new File("task.txt");
            File tempFile = new File("tempTask.txt");

            BufferedReader reader = new BufferedReader(new FileReader(inputFile));
            BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));

            String currentLine;
            while ((currentLine = reader.readLine()) != null) {
                if (!currentLine.equals(taskToDelete)) {
                    writer.write(currentLine);
                    writer.newLine();
                }
            }
            writer.close();
            reader.close();
            inputFile.delete();
            tempFile.renameTo(inputFile);
        } catch (Exception E) {
            JOptionPane.showMessageDialog(null, E.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please select a task to delete");
    }
                                             
    }//GEN-LAST:event_delete_taskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Taks_label;
    private javax.swing.JButton add_task;
    private javax.swing.JButton delete_task;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField task_input;
    private javax.swing.JTable tasks_table;
    // End of variables declaration//GEN-END:variables
}
